- type: message
  text: "Executando suíte de testes Python (pytest)."
- type: command
  command: [".venv/bin/pytest", "samples/core_tests_demo", "-q"]
  cwd: "."
- type: finish
  summary: "Pytest executado."
