llm:
  type: openrouter
  model: "x-ai/grok-4-fast:free"
  base_url: https://openrouter.ai/api/v1
  api_key_env: OPENROUTER_API_KEY

workspace:
  root: .
  allow_outside_root: true

limits:
  max_iterations: 25
  command_timeout: 120
  max_failures: 5

tests:
  auto: false
  commands: []

policies:
  allow_network: true
  allow_shell_write: true

goals:
  apply_patch_success_rate:
    min: 0.9
  actions_success_rate:
    min: 0.85
  tests_success_rate:
    min: 0.95

loop:
  auto_seed: true
  seed_backlog: ../seed/backlog.yaml
  seed_config: seed_manual.yaml
  seed_interval: 0
  stop_when_idle: true

audit:
  enable_file_log: true
  file_dir: seed/changes
  enable_git_commit: true
  low_risk_dry_run: false
  commit_prefix: "A3X"
