llm:
  type: manual
  script: scripts/patch_doc.yaml

workspace:
  root: ..
  allow_outside_root: false

limits:
  max_iterations: 5
  command_timeout: 120
  max_failures: 2

tests:
  auto: false
  commands: []

policies:
  allow_network: false
  allow_shell_write: true

audit:
  enable_file_log: true
  file_dir: seed/changes
  enable_git_commit: false
  commit_prefix: "A3X"

