llm:
  type: manual
  script: scripts/seed_patch.yaml

workspace:
  root: .
  allow_outside_root: false

limits:
  max_iterations: 10
  command_timeout: 120
  max_failures: 3

tests:
  auto: false
  commands: []

policies:
  allow_network: false
  allow_shell_write: true

